# A Brief Intro to Python Classes

## Basic terminology

A "class" is essentially a template for 1) creating and describing of variable, and 2) controlling how that variable can be manipulated. The descriptors associated with all objects of a given class are called "attributes". Functions defined within the class definition, which can operate on any object of a given class once it is created (and only on objects of that class), are called "methods". When we talk about classes, we call individual examples of the class "instances."

It's one of those things that's much easier to show than to explain. Keep an eye out for the terms class, attribute, method, and instance, and how I use them.

If you run Python 3 (as I hope most of you are), a Python class is the same as a data type, which means that integers, floats, lists, tuples, dictionaries, and Boolean values are all classes as well. For Python 2.7 and earlier, types and classes were distinguishable by the fact that Python "types" were also built-in types in C, which is the language of the code running your Python interpreter from behind the scenes.

The unification of class and type has the mildly amusing effect of making the type of any class "type".

In [1]:
print(type(True))
print(type(bool))
print(bool.__class__)

<class 'bool'>
<class 'type'>
<class 'type'>


One of the earliest and best-known classes is the numpy.ndarray. Let's make an array so we can use its familiar attributes and methods to explain attributes and methods in general.

In [2]:
import numpy as np

dummy = np.array([1.,33.,6.,7.,0.5,-0.5,1.,0,10.,10.,9,0.2])
print(dummy)
print(type(dummy))

[ 1.  33.   6.   7.   0.5 -0.5  1.   0.  10.  10.   9.   0.2]
<class 'numpy.ndarray'>


Here, dummy is an "instance" of class numpy.ndarray, one example of that class.

Numpy.ndarray has several attributes you're probably familiar with, like .shape (which, for a 1-D array, is equivalent to its length) and transpose (.T). Attributes are like key-value pairs, if you're familiar with python dictionaries. Attributes can either be passed as arguments to the class or computed automatically upon creating an instance of the class. Regardless, you can access an attribute by simply typing the name of the variable followed by a full-stop and then the name of the attribute.

Methods are called only after a class instance has been created. Again, methods are literally just functions defined inside of a class definition statement. The syntax for calling a method is similar for accessing an attribute, but like regular functions, you must include parentheses after the method name even if the method requires no arguments. Examples of methods for ndarrays include reshape(), sort(), and mean().

Note that you can make arbitrarily long daisy-chains of calls to attributes and methods, in any order.

In [3]:
print(dummy.shape)
print(dummy.ndim)

(12,)
1


In [4]:
b = dummy.reshape((4,3)) #method
print(b,'\n')
print(b.T, b.T.shape) #more attributes

[[ 1.  33.   6. ]
 [ 7.   0.5 -0.5]
 [ 1.   0.  10. ]
 [10.   9.   0.2]] 

[[ 1.   7.   1.  10. ]
 [33.   0.5  0.   9. ]
 [ 6.  -0.5 10.   0.2]] (3, 4)


In [5]:
print(b.reshape((2,6)).T.mean(0))

[7.83333333 5.03333333]


It might be helpful to note that methods tend to require manipulating a copy of the data in memory (e.g. finding the minimum or maximum requires sorting), whereas attributes are typically different ways of viewing the original data (e.g. the transpose is just accessing the same data in a different order). You *could* have your class definition perform calculations with your data automatically for every instance, and assign the results to attributes, but it's generally a better use of computing resources to leave the calculations to your methods and only do them as needed.

## How to Define a class

The first thing you have to do in a class definition is specify how new instances of the class are created. The syntax is:

    class Myclass:
        def __init__(self, args[, ...])
            #more code

Arguments of __init__ (that's "init" with 2 underscores on each side) are what you want to require to create a new instance of this class. The first argument for __init__, and all subsequent methods within the class definition, must be "self" in order for those functions to receive the instance of your class (or, in the case of __init__, to receive the object that will become an instance of your class). Everything after that is optional. Technically a class doesn't have to have methods or attributes (but why would you create an empty class?).

Let's start off with something simple: a class with one mandatory attribute, a couple optional attributes, and one method with a couple optional arguments.

In [6]:
class shark:
    def __init__(self, n_verses, which='Baby',species=None): #'Baby' is the default value of attribute "which"
        self.which = which
        self.n_verses = n_verses
        self.species = species
    
    def sing(self,family=None,segue=False):
        if family is not None:
            if type(family) is str:
                family = [family] #this just lets us enter a string if we only want 2 verses
            family.insert(0,self.which)
        else:
            family = [self.which]
        for s in family:
            for n in range(self.n_verses):
                print('{} shark doo doo doo doo doo doo'.format(s))
            if segue==True:
                print('{} shark!\n'.format(s))
            else:
                print('\n')

            
a = shark(3, 'Mommy')
print('n_verses: {}'.format(a.n_verses))
print('which shark: ',a.which)
print('shark species: ',a.species, '\n') #we didn't set this
a.sing()
print('-----------------------------------------------------')

n_verses: 3
which shark:  Mommy
shark species:  None 

Mommy shark doo doo doo doo doo doo
Mommy shark doo doo doo doo doo doo
Mommy shark doo doo doo doo doo doo


-----------------------------------------------------


You can also modify attributes post-facto, check if a class is allowed to have an attribute with the hasattr() command (helpful if you don't have the source code in front of you), add attributes that you forgot to set with the setattr() command, or delete attributes with the del or delattr() commands. Keep in mind, deleting an attribute is not the same as restoring it to a default value, and setattr() cannot create attributes that are not included in your class defininition. 

In [7]:
a.n_verses=2
a.which='Baby' 
a.sing(['Mommy','Daddy'], segue=True)

print(hasattr(a,'species'), hasattr(a,'rhythm'))
setattr(a,'species','lemon shark')
print(a.species)
del a.species
print('-----------------------------------------------------')

Baby shark doo doo doo doo doo doo
Baby shark doo doo doo doo doo doo
Baby shark!

Mommy shark doo doo doo doo doo doo
Mommy shark doo doo doo doo doo doo
Mommy shark!

Daddy shark doo doo doo doo doo doo
Daddy shark doo doo doo doo doo doo
Daddy shark!

True False
lemon shark
-----------------------------------------------------


As with calling class methods, when creating a new instance of a class, the class name must be followed by parentheses even if __init__ has no required arguments. If n_verses was an optional attribute, you could create a new instance of class shark by setting a variable equal to shark(), but if you forgot the parentheses, your variable would be equal to the class itself.

That brings us to another funny little feature: you can set attributes at the class level if you forgot to add them to your class definition, and all subsequent new instances of that class will start out with that attribute. (This cannot be used to change the default values of attributes already included in the class definition.)

In [8]:
shark.tooth='serrated'
a=shark(4)
print(a.tooth)
a.tooth='conical'
print(a.tooth)
print('-----------------------------------------------------')

serrated
conical
-----------------------------------------------------


One final comment on optional attributes: when you're creating a new instance of a class, note that both required and optional arguments are strictly positional. If you have a large number of optional attributes and you only want to set a specific one somewhere in the middle of the list, it might be better to set the attribute by name after creating the class instance.

## Other Types of Methods
So far the methods I've covered have largely been the standard kind, which take "self" as the first argument. But there are two other kinds of methods: Static and Class methods.

Static methods don't require "self" as an argument, and therefore can be used at both the instance level and the class level. The syntax is pretty much what you'd expect except for one crucial detail: you must type "@staticmethod" on the line above the def line. Let's add one to shark

In [9]:
class shark:
    def __init__(self, n_verses, which='Baby',species=None): #'Baby' is the default value of attribute "which"
        self.which = which
        self.n_verses = n_verses
        self.species = species
    
    def sing(self,family=None,segue=False):
        if family is not None:
            if type(family) is str:
                family = [family] #this just lets us enter a string if we only want 2 verses
            family.insert(0,self.which)
        else:
            family = [self.which]
        for s in family:
            for n in range(self.n_verses):
                print('{} shark doo doo doo doo doo doo'.format(s))
            if segue==True:
                print('{} shark!\n'.format(s))
            else:
                print('\n')
                
    @staticmethod           
    def jaws():
        print("You're gonna need a bigger boat!")

In [10]:
shark.jaws()

You're gonna need a bigger boat!


In [11]:
a=shark(4)
a.jaws()
print('-----------------------------------------------------')

You're gonna need a bigger boat!
-----------------------------------------------------


Class methods receive the class, instead of an instance of the class, as their first argument. They have similar syntax to static methods in that you have to write @classmethod above the method definition. You can also invoke them at both the class and instance level.

There are 2 cases when you would use @classmethod instead of @staticmethod: 1) if your static method calls other static methods (particularly in inherited classes, which I'll get to momentarily), and 2) in the construction of what are called "factory methods". I have neither the knowledge nor the time to cover factory methods, but they sound like a way of dealing with complicated case statements.

In [12]:
class shark:
    n_movies = 6
    def __init__(self, n_verses, which='Baby',species=None): #'Baby' is the default value of attribute "which"
        self.which = which
        self.n_verses = n_verses
        self.species = species
    
    def sing(self,family=None,segue=False):
        if family is not None:
            if type(family) is str:
                family = [family] #this just lets us enter a string if we only want 2 verses
            family.insert(0,self.which)
        else:
            family = [self.which]
        for s in family:
            for n in range(self.n_verses):
                print('{} shark doo doo doo doo doo doo'.format(s))
            if segue==True:
                print('{} shark!\n'.format(s))
            else:
                print('\n')
                
    @staticmethod           
    def jaws():
        print("You're gonna need a bigger boat!")
        
    @classmethod
    def sharknado(cls):
        print("There are {} Sharknado movies.".format(cls.n_movies))

In [13]:
shark.sharknado()

There are 6 Sharknado movies.


In [14]:
a=shark(3)
a.sharknado()

There are 6 Sharknado movies.


In [15]:
shark.n_movies = 4
shark.sharknado()

There are 4 Sharknado movies.


In [16]:
a.sharknado()
print('-----------------------------------------------------')

There are 4 Sharknado movies.
-----------------------------------------------------


This also shows that, with the right syntax, you can modify class attributes and make all instances inherit the changes. That brings us to the next topic: inheritance.

## Class Inheritance

You can create sub-classes that have the same methods and attributes as the main class but also have additional features. The shared features are inherited by the subclass.

There are 2 ways to do it. The first way is to just define the child class with the parent class in parentheses, like so:

In [18]:
class sharkbro(shark):
    def is_sharkbro(self):
        if any(s in self.species for s in ['bull','tiger','great','white']):
            print('Danger! This species is one of the 4 responsible for most fatal attacks!')
        elif any(s in self.species for s in ['tip','reef','blue','mako','lemon','silky','hammerhead']):
            print('Not one of the fatal 4, but still known to attack.')
        else:
            print('No known fatal attacks. Proceed with caution.')
        

In [19]:
a=sharkbro(2,'Daddy','mako')
a.is_sharkbro()
print('-----------------------------------------------------')

Not one of the fatal 4, but still known to attack.
-----------------------------------------------------


In [20]:
a.sing()

Daddy shark doo doo doo doo doo doo
Daddy shark doo doo doo doo doo doo




However, if you include an __init__ statement in a subclass defined this way, you'll override the properties of the parent class. So what do you do if you want to, say, add required attributes but not change what is already included?

You either include a call to the parent function, or more succinctly, use the super() function:

In [24]:
class dancing_shark(shark):
    def __init__(self, n_verses, orientation, which='Baby', species=None):
        super().__init__(n_verses, which, species) #you could replace 'super().__init__(' with 'shark().__init__(self,'
        self.orientation = orientation
    
    def sing(self):
        print('{} shark doo doo doo doo doo doo'.format(self.orientation))

In [25]:
a=dancing_shark(2,'left')
print(a.orientation)
a.sing()

left
left shark doo doo doo doo doo doo


Note that you can insert the sub-class-specific attributes anywhere in the list of attributes after "self". However, note also that optional attributes must be defined again in the first __init__ statement in order to stay optional.
(I experimented with this a bit and I'm still couldn't tell you why it only works this way. Leaving "which" and "species" out of the def __init__ statement makes the class definition fail, defining their default values in the super() statement gives an attribute error saying the attribute is multiply-defined, leaving the default values out of the first __init__ statement made them required for the subclass)

Regardless of which method you use to pass properties of a parent class to a subclass, if you redefine a method in your subclass, the new method definition in the subclass overrides the method definition in the main class.